apiVersion: v1
kind: PersistentVolume
metadata:
  name: weaviate-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /k8s-data/weaviate
