apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-pvc
  namespace: database
spec:
  storageClassName: local-storage
  volumeName: weaviate-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
