apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: database
spec:
  storageClassName: local-storage 
  volumeName: redis-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
