apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  namespace: database
spec:
  storageClassName: local-storage 
  volumeName: neo4j-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
